import 'package:doshop_app/models/exports.dart';
import 'package:doshop_app/utils/constants.dart';

List<CategoryProd> categories = [
  CategoryProd(
    id: 1,
    title: 'Продукты',
    isShown: true,
    hasSubcategories: true,
    img: 'assets/img/categories/grocery.png',
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 2,
    title: 'Алкоголь',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/alcohol.png',
    colorBg: 0xFFB06565,
  ),
  CategoryProd(
    id: 3,
    title: 'Хозтовары',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/hoz.png',
    colorBg: 0xFF5B89B4,
  ),
  CategoryProd(
    id: 4,
    title: 'Химия',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/chem.png',
    colorBg: 0xFF6D5BB4,
  ),
  CategoryProd(
    id: 5,
    title: 'Любимцы',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/pets.png',
    colorBg: 0xFF7FB7AD,
  ),
  CategoryProd(
    id: 6,
    title: 'Одежда, обувь',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/clothes.png',
    colorBg: 0xFFB7977F,
  ),
  CategoryProd(
    id: 7,
    title: 'Сад',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/garden.png',
    colorBg: 0xFF80B77F,
  ),
  CategoryProd(
    id: 8,
    title: 'Аптека',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/pills.png',
    colorBg: 0xFF7F95B7,
  ),
  CategoryProd(
    id: 9,
    title: 'Ребенок',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/baby.png',
    colorBg: 0xFFB77F7F,
  ),
  CategoryProd(
    id: 10,
    title: 'Косметика',
    isShown: true,
    hasSubcategories: false,
    img: 'assets/img/categories/cosmetics.png',
    colorBg: 0xFFB77FA1,
  ),
  CategoryProd(
    id: 11,
    title: 'Мясо',
    subtitle: 'мясопродукты',
    isShown: true,
    img: 'assets/img/categories/meat.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 12,
    title: 'Рыба',
    subtitle: 'рыбопродукты',
    isShown: true,
    img: 'assets/img/categories/fish.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 13,
    title: 'Сыр',
    subtitle: 'молоко йогурт',
    isShown: true,
    img: 'assets/img/categories/milk_cheese.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 14,
    title: 'Бакалея',
    subtitle: 'крупа, соль, сахар, масло, яйцо',
    isShown: true,
    img: 'assets/img/categories/bakaleya.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 15,
    title: 'Специи',
    subtitle: 'перец, розмарин...',
    isShown: true,
    img: 'assets/img/categories/species.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
  CategoryProd(
    id: 16,
    title: 'Овощи',
    subtitle: 'фрукты, ягоды, зелень',
    isShown: true,
    img: 'assets/img/categories/fruit1.png',
    parentId: 1,
    hasSubcategories: false,
    isSubcat: true,
    colorBg: 0xFF7F83B7,
  ),
];


List<Product> products = [
  Product(
    id: 1,
    catId: 11,
    title: "Курица",
    subtitle: 'Охлажденая',
    units: Units.thing,
    icon: 'assets/icons/grocery/chicken.png',
    tag: 'Курица',
  ),
  Product(
    id: 2,
    catId: 11,
    title: "Курица четверть",
    units: Units.kg,
    icon: 'assets/icons/grocery/hen_repair.png',
    tag: 'Курица',
  ),
  Product(
    id: 3,
    catId: 11,
    title: "Курица крылья",
    units: Units.kg,
    icon: 'assets/icons/grocery/hen_repair.png',
    tag: 'Курица',
  ),
  Product(
    id: 4,
    catId: 11,
    title: "Курица филе",
    units: Units.kg,
    icon: 'assets/icons/grocery/hen_repair.png',
    tag: 'Курица',
  ),
  Product(
    id: 5,
    catId: 11,
    title: "Индейка филе",
    units: Units.kg,
    icon: 'assets/icons/grocery/hen_repair.png',
    tag: 'Индейка',
  ),
  Product(
    id: 6,
    catId: 11,
    title: "Индейка бедро",
    units: Units.kg,
    icon: 'assets/icons/grocery/hen_repair.png',
    tag: 'Индейка',
  ),
  Product(
    id: 7,
    catId: 11,
    title: "Говядина филе",
    units: Units.kg,
    icon: 'assets/icons/grocery/steak.png',
    tag: 'Говядина',
  ),
  Product(
      id: 8,
      catId: 11,
      title: "Говядина ребро",
      units: Units.kg,
      icon: 'assets/icons/grocery/steak.png',
      tag: 'Говядина'),
  Product(
    id: 9,
    catId: 11,
    title: "Свинина ребро",
    subtitle: 'Свежее',
    units: Units.kg,
    icon: 'assets/icons/grocery/big_leg.png',
    tag: 'Свинина',
  ),
  Product(
    id: 10,
    catId: 11,
    title: "Свинина филе",
    subtitle: 'Свежее',
    units: Units.kg,
    icon: 'assets/icons/grocery/big_leg.png',
    tag: 'Свинина',
  ),
  Product(
    id: 11,
    catId: 11,
    title: "Свинина шея",
    subtitle: 'Заморозка',
    units: Units.kg,
    icon: 'assets/icons/grocery/big_leg.png',
    tag: 'Свинина',
  ),
  Product(
    id: 12,
    catId: 11,
    title: "Свинина подчеревок",
    subtitle: 'Копченный',
    units: Units.kg,
    icon: 'assets/icons/grocery/kolbasa.png',
    tag: 'Мясопродкуты',
  ),
  Product(
    id: 13,
    catId: 11,
    title: "Свинина подчеревок",
    subtitle: 'Свежее',
    units: Units.kg,
    icon: 'assets/icons/grocery/big_leg.png',
    tag: 'Свинина',
  ),
  Product(
    id: 14,
    catId: 11,
    title: "колбаса сыровяленая",
    units: Units.kg,
    icon: 'assets/icons/grocery/kolbasa.png',
    tag: 'Мясопродкуты',
  ),
  Product(
    id: 15,
    catId: 11,
    title: "колбаса вареная",
    units: Units.kg,
    icon: 'assets/icons/grocery/kolbasa.png',
    tag: 'Мясопродкуты',
  ),
  Product(
    id: 16,
    catId: 11,
    title: "Сосиски",
    units: Units.kg,
    icon: 'assets/icons/grocery/kolbasa.png',
    tag: 'Мясопродкуты',
  ),
  Product(
    id: 17,
    catId: 11,
    title: "Сардельки",
    units: Units.kg,
    icon: 'assets/icons/grocery/kolbasa.png',
    tag: 'Мясопродкуты',
  ),
  // Milk
  Product(
    id: 18,
    catId: 13,
    title: "Молоко 2,5%",
    subtitle: 'Веселый фермер',
    units: Units.lt,
    icon: 'assets/icons/grocery/milk.png',
    tag: 'Молоко',
  ),
  Product(
    id: 19,
    catId: 13,
    title: "Сыр гауда",
    subtitle: 'Веселый фермер',
    units: Units.lt,
    icon: 'assets/icons/grocery/cheese.png',
    tag: 'Сыр',
  ),
  Product(
    id: 20,
    catId: 13,
    title: "Сыр плавленый",
    subtitle: 'Веселый фермер',
    units: Units.lt,
    icon: 'assets/icons/grocery/cheese.png',
    tag: 'Сыр',
  ),
  Product(
    id: 21,
    catId: 13,
    title: "Йогурт",
    subtitle: 'Веселый фермер',
    units: Units.lt,
    icon: 'assets/icons/grocery/yogurt.png',
    tag: 'Молокопродукты',
  ),
  // Fish
  Product(
    id: 22,
    catId: 12,
    title: "Хек",
    subtitle: 'Заморозка',
    units: Units.kg,
    tag: 'Мороз',
  ),
  Product(
    id: 23,
    catId: 12,
    title: "Минтай",
    subtitle: 'Заморозка',
    units: Units.kg,
    tag: 'Мороз',
  ),
  Product(
    id: 24,
    catId: 12,
    title: "Семга",
    subtitle: 'Заморозка',
    units: Units.kg,
    tag: 'Мороз',
  ),
  Product(
    id: 25,
    catId: 12,
    title: "Скумбрия",
    subtitle: 'Заморозка',
    units: Units.kg,
    tag: 'Маринад',
  ),
  Product(
    id: 26,
    catId: 12,
    title: "Селедка",
    subtitle: 'Соленая',
    units: Units.kg,
    tag: 'Маринад',
  ),
  Product(
    id: 27,
    catId: 12,
    title: "Морская капуста",
    subtitle: 'Готовая',
    units: Units.kg,
    tag: 'Морепродукты',
  ),
// bakaleya
  Product(
    id: 28,
    catId: 14,
    title: "Хлопья Овсяные",
    subtitle: 'Хуторок',
    units: Units.kg,
    tag: 'Хлопья',
  ),
  Product(
    id: 29,
    catId: 14,
    title: "Хлопья 7 злаков",
    subtitle: 'Хуторок',
    units: Units.kg,
    tag: 'Хлопья',
  ),
  Product(
    id: 30,
    catId: 14,
    title: "Крупа гречневая",
    subtitle: 'Хуторок',
    units: Units.kg,
    tag: 'Крупа',
  ),
  Product(
    id: 31,
    catId: 14,
    title: "Крупа кукурузная",
    subtitle: 'Хуторок',
    units: Units.kg,
    tag: 'Крупа',
  ),
  Product(
    id: 32,
    catId: 14,
    title: "Лапша",
    units: Units.kg,
    tag: 'Pasta',
  ),
  Product(
    id: 33,
    catId: 14,
    title: "Соль",
    units: Units.kg,
    tag: '# 1',
  ),
  Product(
    id: 34,
    catId: 14,
    title: "Сахар песок",
    units: Units.kg,
    tag: '# 1',
  ),
  Product(
    id: 35,
    catId: 14,
    title: "Масло подсолнечное",
    units: Units.lt,
    tag: '# 1',
  ),
  Product(
    id: 36,
    catId: 14,
    title: "Яйца",
    units: Units.thing,
    tag: '# 1',
  ),
// species
  Product(
    id: 37,
    catId: 15,
    title: "Хмели-сунели",
    units: Units.pack,
  ),
  Product(
    id: 38,
    catId: 15,
    title: "Куркума",
    subtitle: 'Пластиковая упаковка',
    units: Units.pack,
  ),
  Product(
    id: 39,
    catId: 15,
    title: "Розмарин",
    units: Units.pack,
  ),
  Product(
    id: 40,
    catId: 15,
    title: "Перец черный",
    units: Units.pack,
  ),
  Product(
    id: 41,
    catId: 15,
    title: "Перец красный",
    units: Units.pack,
  ),
  Product(
    id: 42,
    catId: 15,
    title: "Приправа для плова",
    subtitle: 'На развес у Алика',
    units: Units.pack,
  ),
  Product(
    id: 43,
    catId: 15,
    title: "Приправа для рыбы",
    units: Units.pack,
  ),

// vegitables
  Product(
    id: 44,
    catId: 16,
    title: "Картофель",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 45,
    catId: 16,
    title: "Капуста",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 46,
    catId: 16,
    title: "Морковь",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 47,
    catId: 16,
    title: "Свекла",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 48,
    catId: 16,
    title: "Лук репчатый",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 49,
    catId: 16,
    title: "Чеснок",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 50,
    catId: 16,
    title: "Помидор",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 51,
    catId: 16,
    title: "Огурец",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 52,
    catId: 16,
    title: "Перец",
    units: Units.kg,
    tag: 'Овощи',
  ),
  Product(
    id: 53,
    catId: 16,
    title: "Яблоки",
    units: Units.kg,
    tag: 'Фрукты',
  ),
  Product(
    id: 54,
    catId: 16,
    title: "Апельсины",
    units: Units.kg,
    tag: 'Фрукты',
  ),
  Product(
    id: 55,
    catId: 16,
    title: "Бананы",
    units: Units.kg,
    tag: 'Фрукты',
  ),
  Product(
    id: 56,
    catId: 16,
    title: "Укроп",
    units: Units.pack,
    tag: 'Зелень',
  ),
  Product(
    id: 57,
    catId: 16,
    title: "Петрушка",
    units: Units.pack,
    tag: 'Зелень',
  ),
  Product(
    id: 58,
    catId: 16,
    title: "Сельдирей",
    units: Units.pack,
    tag: 'Зелень',
  ),
  //Alcohol
  Product(
    id: 59,
    catId: 2,
    title: "Водочка 0.5л",
    subtitle: 'Самжене',
    units: Units.thing,
    tag: 'Крепкие',
  ),
  Product(
    id: 60,
    catId: 2,
    title: "Коньяк",
    subtitle: 'Армянский 0.7',
    units: Units.thing,
    tag: 'Крепкие',
  ),
  Product(
    id: 61,
    catId: 2,
    title: "Бренди",
    units: Units.thing,
    tag: 'Крепкие',
  ),
  Product(
    id: 62,
    catId: 2,
    title: "Виски",
    units: Units.thing,
    tag: 'Крепкие',
  ),
  Product(
    id: 63,
    catId: 2,
    title: "Пиво 2,5л",
    subtitle: 'Лвiвське',
    units: Units.thing,
    tag: 'Легкие',
  ),
  Product(
    id: 92,
    catId: 2,
    title: "Пиво 0,5л",
    subtitle: 'Арсенал',
    units: Units.thing,
    tag: 'Легкие',
  ),
  // hoz
  Product(
    id: 64,
    catId: 3,
    title: "Губка для посуды",
    subtitle: 'Фрекен Бок',
    units: Units.pack,
    tag: 'Кухня',
  ),
  Product(
    id: 65,
    catId: 3,
    title: "Полотенце для рук",
    subtitle: 'Вафельное',
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 66,
    catId: 3,
    title: "Полотенца одноразовые",
    subtitle: 'Мамына бусинка',
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 67,
    catId: 3,
    title: "Салфетки",
    subtitle: 'Мамына бусинка',
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 68,
    catId: 3,
    title: "Спички",
    subtitle: 'Мамын Праказник',
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 69,
    catId: 3,
    title: "Зажигалка",
    subtitle: 'Пьезо',
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 70,
    catId: 3,
    title: "Мочалка",
    subtitle: 'Грязнулька',
    units: Units.thing,
    tag: 'Санузел',
  ),
  Product(
    id: 71,
    catId: 3,
    title: "Туалетная бумага",
    subtitle: 'Грязнулька',
    units: Units.thing,
    tag: 'Санузел',
  ),
  Product(
    id: 72,
    catId: 3,
    title: "Полотенце для рук",
    subtitle: 'Грязнулька',
    units: Units.thing,
    tag: 'Санузел',
  ),
  Product(
    id: 73,
    catId: 3,
    title: "Перчатки резиновые",
    units: Units.thing,
    tag: 'Уборка',
  ),
  Product(
    id: 74,
    catId: 3,
    title: "Ветошь для пола",
    units: Units.thing,
    tag: 'Уборка',
  ),
  Product(
    id: 75,
    catId: 3,
    title: "Ветошь для мебели",
    units: Units.thing,
    tag: 'Уборка',
  ),
  Product(
    id: 76,
    catId: 3,
    title: "Веник",
    units: Units.thing,
    tag: 'Уборка',
  ),
  //chem
  Product(
    id: 77,
    catId: 4,
    title: "Стиральный порошок",
    units: Units.thing,
    tag: 'Стирка',
  ),
  Product(
    id: 78,
    catId: 4,
    title: "Выполаскиватель",
    units: Units.thing,
    tag: 'Стирка',
  ),
  Product(
    id: 79,
    catId: 4,
    title: "Жидкое мыло",
    units: Units.thing,
    tag: 'Ванная',
  ),
  Product(
    id: 80,
    catId: 4,
    title: "Шампунь",
    units: Units.thing,
    tag: 'Ванная',
  ),
  Product(
    id: 81,
    catId: 4,
    title: "Гель для душа",
    units: Units.thing,
    tag: 'Ванная',
  ),
  Product(
    id: 82,
    catId: 4,
    title: "Посуда моющее",
    units: Units.thing,
    tag: 'Кухня',
  ),
  Product(
    id: 83,
    catId: 4,
    title: "Освежитель воздуха",
    units: Units.thing,
    tag: 'Туалет',
  ),
  // Zoo
  Product(
    id: 84,
    catId: 5,
    title: "Корм",
    units: Units.kg,
    tag: 'Еда',
  ),
  Product(
    id: 85,
    catId: 5,
    title: "Наполнитель в лоток",
    units: Units.thing,
    tag: 'Лоток',
  ),
  // Clothes
  Product(
    id: 86,
    catId: 6,
    title: "Носки",
    subtitle: 'Катоновые',
    units: Units.couple,
    tag: 'Весна-лето',
  ),
  Product(
    id: 87,
    catId: 6,
    title: "Носки теплые",
    units: Units.couple,
    tag: 'Зима',
  ),
  Product(
    id: 88,
    catId: 6,
    title: "Трусы мужские",
    units: Units.thing,
    tag: 'Нижнее белье',
  ),
  Product(
    id: 89,
    catId: 6,
    title: "Трусы женские",
    units: Units.thing,
    tag: 'Нижнее белье',
  ),
  Product(
    id: 90,
    catId: 6,
    title: "Купальник",
    units: Units.thing,
    tag: 'Лето',
  ),
  Product(
    id: 91,
    catId: 6,
    title: "Плавки",
    units: Units.thing,
    tag: 'Лето',
  ),
  // skip
  Product(
    id: 93,
    catId: 6,
    title: "Футболка",
    units: Units.thing,
    tag: 'Лето',
  ),
];
